# [en]
#   title = "Maxwell"
#   LanguageName = "English"
#   weight = 2
[zh-CN]
  title = "Maxwell" # just for the sake of showing this is possible
  LanguageName = "简体中文"
  weight = 1

  # tip: assign the default language the lowest Weight